
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird crash_course_september_git - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
    jobs:
      cd:  # deploy changes to workspace 'crash_course_september_git'
        uses: tinybirdco/ci/.github/workflows/cd.yml@v4.1.0
        secrets:
          tb_admin_token: ${{ secrets.TB_CRASH_COURSE_SEPTEMBER_GIT_ADMIN_TOKEN }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://api.us-east.aws.tinybird.co
